### ISSUE TITLE
How to start with this event script

### ISSUE THREAD

**Issue by chinmaywavekar** [dataclay/event-scripts#1] opened 2019-10-23 05:15 UTC
Hello,

I am new on this platform.
I want to use node js event script for my command line templater bot.

can you please help me out to use this script code ..

Thanks

**Comment by blakmarkit** [comment] 2019-10-23 15:41
@chinmaywavekar 

Have you read the documentation on the [event scripts readme](https://github.com/dataclay/event-scripts#event-scripts-for-templater)? Also, there is extensive documentation on our [support website](http://support.dataclay.com/content/concepts/bot/event_scripts.htm). You can also check [our website](https://dataclay.com/support/), with links to screencasts, forums, and forms to submit support tickets. 

I'm going to close this issue as it is not a bugfix or feature request.

**Closed by blakmarkit** 2019-10-23 15:41 UTC
